import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import Navbar from "@/components/Navbar";
import MainLayout from "@/components/MainLayout";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        theme: dark,
        elements: {
          cardBox: "!border !border-white/20",
        },
      }}
    >
      <html lang="en" className="dark">
        <body
          className={`${spaceGrotesk.variable} ${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased`}
        >
          <ConvexClientProvider>
            <MainLayout Navbar={<Navbar />}>{children}</MainLayout>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
